#!/bin/bash
# Git pre-commit 钩子安装脚本
# 用于自动安装敏感信息检测钩子

set -e  # 遇到错误立即退出

# ============ 常量定义 ============

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
PRE_COMMIT_HOOK="$HOOKS_DIR/pre-commit"
CONFIG_FILE="$PROJECT_ROOT/config/sensitive-rules.yaml"
CHECK_SCRIPT="$PROJECT_ROOT/scripts/sensitive-check.ts"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============ 工具函数 ============

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# ============ 检查函数 ============

check_git_repo() {
    if [ ! -d "$PROJECT_ROOT/.git" ]; then
        log_error "当前目录不是 Git 仓库"
        log_info "请在 Git 仓库根目录下运行此脚本"
        exit 1
    fi
}

check_config_file() {
    if [ ! -f "$CONFIG_FILE" ]; then
        log_error "配置文件不存在: $CONFIG_FILE"
        log_info "请先创建配置文件，参考项目文档"
        exit 1
    fi
}

check_check_script() {
    if [ ! -f "$CHECK_SCRIPT" ]; then
        log_error "检测脚本不存在: $CHECK_SCRIPT"
        log_info "请确保项目文件完整"
        exit 1
    fi
}

check_node() {
    if ! command -v node >/dev/null 2>&1; then
        log_error "未找到 Node.js"
        log_info "请先安装 Node.js: https://nodejs.org/"
        exit 1
    fi
    
    NODE_VERSION=$(node -v)
    log_info "Node.js 版本: $NODE_VERSION"
}

# ============ 安装函数 ============

backup_existing_hook() {
    if [ -f "$PRE_COMMIT_HOOK" ]; then
        BACKUP_FILE="${PRE_COMMIT_HOOK}.backup.$(date +%Y%m%d_%H%M%S)"
        log_warning "检测到已存在的 pre-commit 钩子"
        log_info "备份到: $BACKUP_FILE"
        cp "$PRE_COMMIT_HOOK" "$BACKUP_FILE"
        return 0
    fi
    return 1
}

install_hook() {
    log_info "正在创建 pre-commit 钩子..."
    
    # 确保 hooks 目录存在
    mkdir -p "$HOOKS_DIR"
    
    # 创建 pre-commit 钩子文件
    cat > "$PRE_COMMIT_HOOK" << 'HOOK_EOF'
#!/bin/sh
# Git pre-commit hook for sensitive information check
# Auto-generated by scripts/install-hooks.sh

# 获取项目根目录
PROJECT_ROOT="$(git rev-parse --show-toplevel)"
cd "$PROJECT_ROOT" || exit 1

# 检查 Node.js 环境
if ! command -v node >/dev/null 2>&1; then
    echo "❌ 未找到 Node.js，请先安装 Node.js"
    echo "💡 提示: 可使用 git commit --no-verify 跳过检查"
    exit 1
fi

# 检查配置文件
if [ ! -f "config/sensitive-rules.yaml" ]; then
    echo "⚠️  未找到配置文件: config/sensitive-rules.yaml"
    echo "跳过敏感信息检查"
    exit 0
fi

# 检查检测脚本
if [ ! -f "scripts/sensitive-check.ts" ]; then
    echo "⚠️  未找到检测脚本: scripts/sensitive-check.ts"
    echo "跳过敏感信息检查"
    exit 0
fi

# 执行敏感信息检查
echo ""
echo "================================"
echo "  🔍 敏感信息检查"
echo "================================"
echo ""

npx tsx scripts/sensitive-check.ts
CHECK_RESULT=$?

if [ $CHECK_RESULT -ne 0 ]; then
    echo ""
    echo "================================"
    echo "  ❌ 提交被阻止"
    echo "================================"
    echo ""
    echo "💡 提示:"
    echo "  - 请移除敏感信息后重新提交"
    echo "  - 使用 git commit --no-verify 可跳过检查（不推荐）"
    echo "  - 编辑 config/sensitive-rules.yaml 自定义规则"
    echo ""
    exit 1
fi

exit 0
HOOK_EOF

    # 添加执行权限
    chmod +x "$PRE_COMMIT_HOOK"
    
    log_success "pre-commit 钩子创建成功"
}

show_usage() {
    echo ""
    echo "================================"
    echo "  📚 使用说明"
    echo "================================"
    echo ""
    echo "1️⃣  钩子位置:"
    echo "   $PRE_COMMIT_HOOK"
    echo ""
    echo "2️⃣  配置文件:"
    echo "   $CONFIG_FILE"
    echo ""
    echo "3️⃣  检测脚本:"
    echo "   $CHECK_SCRIPT"
    echo ""
    echo "4️⃣  自定义规则:"
    echo "   编辑 config/sensitive-rules.yaml 添加或修改检测规则"
    echo ""
    echo "5️⃣  测试钩子:"
    echo "   git add <file>"
    echo "   git commit -m \"test\""
    echo ""
    echo "6️⃣  跳过检查:"
    echo "   git commit --no-verify -m \"message\""
    echo ""
    echo "7️⃣  卸载钩子:"
    echo "   rm $PRE_COMMIT_HOOK"
    echo ""
    echo "8️⃣  手动运行检查:"
    echo "   npm run check:sensitive"
    echo ""
}

# ============ 主函数 ============

main() {
    echo ""
    echo "================================"
    echo "  🔧 Git Pre-commit 钩子安装程序"
    echo "================================"
    echo ""
    
    # 1. 环境检查
    log_info "正在检查环境..."
    check_git_repo
    check_config_file
    check_check_script
    check_node
    log_success "环境检查通过"
    echo ""
    
    # 2. 备份现有钩子
    if backup_existing_hook; then
        log_success "已备份现有钩子"
        echo ""
    fi
    
    # 3. 安装钩子
    install_hook
    echo ""
    
    # 4. 验证安装
    if [ -x "$PRE_COMMIT_HOOK" ]; then
        log_success "钩子安装完成并具有执行权限"
    else
        log_error "钩子安装失败：缺少执行权限"
        exit 1
    fi
    echo ""
    
    # 5. 显示使用说明
    show_usage
    
    log_success "安装完成！现在每次提交代码时都会自动检查敏感信息"
    echo ""
}

# 执行主函数
main "$@"
